//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.17 at 01:35:30 PM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/api/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.spring.web.market.products_ws.xsd;
